### ISSUE TITLE
iele.contractCall and iele.createContract won't accept non Integers. 

### ISSUE THREAD

**Issue by carloslodelar** [input-output-hk/mallet#11]
Playing around with a basic "hello world" contract. It worked well in IELE using https://iele-testnet.iohkdev.io/  But...

Perhaps I'm doing something wrong, but I can't get mallet to accept values different to integers when creating or calling a contract: 

`mallet> let bytecode = '0000037463046900096D65737361676528296900127365744D65737361676528737472696E672969001B7365744D65737361676528737472696E67292E696E7465726E616C69001669656C6572742E6D656D6F72792E616C6C6F6361746569001269656C6572742E6D656D6F72792E66696C6C69001369656C6572742E73746F726167652E66696C6C69001C69656C6572742E6D656D6F72792E636F70792E746F2E6D656D6F727969001D69656C6572742E6D656D6F72792E636F70792E746F2E73746F7261676569001D69656C6572742E73746F726167652E636F70792E746F2E6D656D6F727969001E69656C6572742E73746F726167652E636F70792E746F2E73746F72616765680001000066000034006500010061010151126101010101236101015313610101010133618004610101541561080652643501064461010161010701071854890D095A52543A010544513BF600010B660001620101F7016700000001660000340165000201610102512361010201023461010253246101020102445340618005610202F800040001000126606761080850854901085550954A0C0A9A0D0A9A010955536961010201026B53BA607061010261020CF80008000300000C20660001F60000660002620102F7026800020001660000340165000101610102512361010201023461010253246101020102445340618005610202F800040001000126606761080850854901085550954A0C0A9A0D0A9A010955536961010201026B53BA6070F800030001000000F60000660001620102F7026700030001660000610101610202F80008000300000210660001F60000670004000166000061010151126102010101230100226101015312F600010367000500036600001513650001035302610104010400610104030411640000660001F6000067000600036600001513650001035502610104010400610104030411640000660001F60000670007000366000015236500010351045314610105010500610105010511610105030522640000660001F60000670008000366000015236500010351045514610105010500610105010511610105030522640000660001F60000670009000366000015236500010354045314610105010500610105010511610105030522640000660001F6000067000A000366000015236500010354045514610105010500610105010511610105030522640000660001F60000'
undefined
mallet> iele.createContract({gas: 1000000, value: 0, code: bytecode, func: 'setMessage(string)', args: ['hello world']})
**SyntaxError: Cannot convert hello world to a BigInt**

mallet> 
`

Do you intend to improve this behavior? perhaps I need to call another function? Or should we stick to integers only?

**Comment by rtkaczyk** [comment]
Hi @carloslodelar, the functionality you require has already been added in the `develop` branch. I expect it to be merged sometime this week.

In the meantime you can just switch to `develop`. See this [note on types encoding](https://github.com/input-output-hk/mallet/tree/develop#note-on-type-encoding).

In your case you will need to replace: `'hello world'` with `iele.enc('hello world', 'string')`. Notice also that `createContract` was renamed to `deployContract`.

**Comment by carloslodelar** [comment]
That's good news. Thanks @rtkaczyk . Good wording selection for the rename!

**Comment by rtkaczyk** [comment]
Fixed by merging #12
